### ISSUE TITLE
Don’t use Cmd+H as the Dash shortcut (breaks system Hide function)

### ISSUE THREAD

**Issue by natesilva** [deerawan/vscode-dash#1]
The shortcut <kbd>Cmd</kbd>+<kbd>H</kbd> is the Mac’s system shortcut to hide the current window. The Dash extension should use a different key combo. ([Don’t be like Photoshop!](http://daringfireball.net/linked/2008/06/02/nack))

Instead, consider using <kbd>Ctrl</kbd>+<kbd>H</kbd>. That’s the shortcut used by the Dash plugins for both [Sublime Text](https://github.com/farcaller/DashDoc#readme) and [Atom](https://github.com/blakeembrey/atom-dash#readme). You would use <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>H</kbd> to search all documentation (same as the Atom Dash plugin).

**Comment by deerawan** [comment]
Hi @natesilva 

Thank you for your suggestion. You are correct, these shortcuts are more make sense to use. I have updated the extension to version 1.1.1 which support the shortcuts.

**Comment by natesilva** [comment]
Works great. Thanks!

**Comment by y-usuzumi** [comment]
@deerawan Request reopen this issue.

For Linux (not so sure about Windows though), Ctrl + H is the default key binding for "Replace" (`editor.action.startFindReplaceAction`), and Ctrl + Shift + H is for "Replace in files" (`workbench.action.replaceInFiles`), which are both very fundamental and frequently used default key bindings.

I think it might be better to use something else.

**Comment by davidkwan95** [comment]
can we just make so the keybinding is configurable? I encountered the problem with overlapping the replace command with this extension, and I don't want to change my keybind for replace since I've been using it for a long time.
