### ISSUE TITLE
support for linux?

### ISSUE THREAD

**Issue by tracure1337** [deerawan/vscode-dash#109]
The ext is only available in vscode macos and windows?

Or what am I doing wrong?

**Comment by lidorcg** [comment]
Are you having problem finding? installing? or using the ext?

I ask because I have ubuntu and I can find & install the ext just fine in the extensions market.
I do have some problem with getting it to work ATM (but it definitely worked in the past)

**Comment by tracure1337** [comment]
@lidorcg  thanks :) That was a while ago. I just checked and works like a charm!
