### ISSUE TITLE
mistake title description

### ISSUE THREAD

**Issue by weifding** [deerawan/vscode-dash#14]
In Package.json
> {
>         "command": "extension.dash.emptySyntax",
>         "title": "Search in Dash for current language documentation"
>       },
I think it should be "Open Dash for current language documentation"
When press F1,and text "dash" in command input box, this decription confused me....

**Comment by deerawan** [comment]
Thank you @weifding for your feedback. Seems your suggestion is better. Will change the text in the next version. 👍

**Comment by deerawan** [comment]
Solves in https://github.com/deerawan/vscode-dash/pull/13
