### ISSUE TITLE
How to search selection only in the profile currently active?

### ISSUE THREAD

**Issue by nikitavoloboev** [deerawan/vscode-dash#19]
For example I have a profile active that searches through Go and some specified go libraries like so : 

![2017-11-04 at 18 25](https://user-images.githubusercontent.com/6391776/32407741-93b1bba8-c18d-11e7-9e48-c6e63f40fa92.png)

Can you please add action that will search selection only in the currently active profile?

Thank you.

**Comment by deerawan** [comment]
Hi @nikitavoloboev 

Interesting. I will have a look at this.

**Comment by deerawan** [comment]
@nikitavoloboev I threw a question about this one too to Dash developer. Seems like there is no support for this from them literally.

**Comment by deerawan** [comment]
Duplicate with https://github.com/deerawan/vscode-dash/issues/44
