### ISSUE TITLE
Does not detect language currently in use

### ISSUE THREAD

**Issue by nach00** [deerawan/vscode-dash#24]
Hi,

I was using Zeal in Sublime Text 3 before, and when I hit F1, it automatically searched for the syntax in the programming language set for the document. For example:
I will be coding in a Ruby (.rb) document, and hit F1 on "class". This pulls up ruby:class documentation automatically. When I switched to a Python document, it does so for this automatically as well.
Does your extension have a feature that does this? For now, in VBC, when I hit Shift-F1 on "class", it will search for all docs containing "class".

Am I doing something wrong? I know I can set a specific hotkey for searching Ruby syntax and Python syntax specifically, but I'd like to avoid that. Thank you.

I'm currently using Ubuntu 16.04.2 LTS 64-bit

**Comment by deerawan** [comment]
Hi @nach00, 

I'm afraid you need install language plugin for Ruby first in VS Code. https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby. So, VS Code can support this language. Try to install it and re-test the Dash again.

**Comment by deerawan** [comment]
Issue is closed since no further response 😄
