### ISSUE TITLE
Custom file formats

### ISSUE THREAD

**Issue by Yanpas** [deerawan/vscode-dash#25]
I use gdscript language. Please add a way to register custom file extensions. Something like:
```
"dash.docset.other": {
  "gd" :  [
        "godot"
    ],
}
```

**Comment by deerawan** [comment]
Hi @Yanpas, 

I'm not sure that will work in vs code `configuration` field in `package.json`. Alternatively, we can add support for `gdscript` as I check that the extension is exist for it https://marketplace.visualstudio.com/items?itemName=jjkim.gdscript

What do you think?

**Comment by Yanpas** [comment]
Good option, but there is no official godot docset. On the other hand I doubt that it can be named other "godot"

**Comment by deerawan** [comment]
@Yanpas ah yes, you're right. There is no godot docset for Dash. Perhaps you can try to contribute there https://kapeli.com/docsets

**Comment by kogent** [comment]
It seems like as long as the language is set in vscode and there is a matching dash key then it works, if not then you have to setup a dash.docset.lang definition that maps to a key in dash.

The only problem I've seen here is that the settings.json validation complains with `Unknown Configuration Setting` warnings if the lang definition is one that not part of the default set.

eg- I have ansible-advanced being detected so to make that work I setup:
```json
    "dash.docset.ansible-advanced": [
        "ansible"
    ]
```
`ctrl-h` now correctly does lookups in the ansible docset but vscode shows the warning.
