### ISSUE TITLE
Add Terraform support

### ISSUE THREAD

**Issue by deerawan** [deerawan/vscode-dash#26]
Extension Link
https://marketplace.visualstudio.com/items?itemName=mauve.terraform

**Comment by kogent** [comment]
I have that extension installed and am able to press ctrl-h on a resource or datasource definition and have it correctly look up the Terraform user contributed docset.

**Comment by deerawan** [comment]
@kogent did you add anything to `settings.json`?

**Comment by kogent** [comment]
Here's a gist of my settings.json: 
https://gist.github.com/kogent/a7b3658d7b611d78823e27b68214f1da

**Comment by deerawan** [comment]
@kogent thank you for sharing the file. 

Yes, the plugin can detect the docset based on your `settings.json`. 👍
