### ISSUE TITLE
On Ctrl+H it searches on all languages, not the currently used one

### ISSUE THREAD

**Issue by kraklin** [deerawan/vscode-dash#3]
On MacOS Sierra, when I hit ctrl-H it runs dash, but the search shows all languages.

**Comment by deerawan** [comment]
Hi @kraklin

Will note the about this issue. I haven't upgraded my OS to Sierra due to some incompatible softwares like office and screenflow in my end. 

Thank you

**Comment by kraklin** [comment]
It's just a minor issue. :) Keep up great work on this plugin ;)

**Comment by deerawan** [comment]
@kraklin Hi Kraklin, 

Do you remember the extension of file that you were searching in?

**Comment by kraklin** [comment]
Hi,
it was Elm or Javascript. I tried them both now, JS is opening the right search within JS docs, although it is not searching for array.fill on [].fill(). It searched for animation something .fill method. But this is not the problem of plugin, dash behaves the same when I try to search it for myself.

Elm goes right to Google search inside Dash.

**Comment by deerawan** [comment]
Hi @kraklin 

I just released v1.3.0 that supports elm. 🎉 🎉
https://marketplace.visualstudio.com/items?itemName=deerawan.vscode-dash

Make sure you install elm vscode plugins first
https://marketplace.visualstudio.com/items?itemName=sbrink.elm

Let me know if it solves your issue 😃

**Comment by kraklin** [comment]
Hi, I totally forgot to mention that... It works!!! :champagne: 👍 

Thank you

**Comment by deerawan** [comment]
glad to hear that 👍
