### ISSUE TITLE
Ctrl + H Fails to Work for Java File

### ISSUE THREAD

**Issue by xlinshan** [deerawan/vscode-dash#31]
My environment is VSC 1.24.1 on macOS 10.13.5, with the Java Language Support extension installed.

Pressing ctrl + h has no response, but ctrl + alt + h, ctrl + shift + h, and alt + h do work as descripted in the document.

**Comment by xlinshan** [comment]
It turns out that there were other actions already bound to ctrl + h by the vim extension.

**Comment by deerawan** [comment]
@xlinshan you can change dash keyboard shortcut to something else
https://github.com/deerawan/vscode-dash#change-keyboard-shortcut

I'll close this ticket and will consider whether we want to change the default shortcut. 

Thank you @xlinshan 👍
