### ISSUE TITLE
`dash.docset.` settings do not work

### ISSUE THREAD

**Issue by nikitavoloboev** [deerawan/vscode-dash#33]
I added this to my `settings.js` file:

```json
  "dash.docset.typescript": [
    "typescript",
    "javascript"
  ],
```

Assuming that it will only search these two docsets when you run the Dash hotkey in `.ts` files but that did nothing. It still searches through all these docsets:

![2018-08-02 at 14 45](https://user-images.githubusercontent.com/6391776/43584453-b51257e4-9662-11e8-976a-c211d36f941c.png)

Is this a bug? Or I did something wrong?

**Comment by deerawan** [comment]
Hi @nikitavoloboev 

I also can reproduce your issue. I threw a question to the Dash developer regarding this. Will keep you posted. 

Thank you

**Comment by deerawan** [comment]
@nikitavoloboev 

Got this answer from author of Dash
> if you send "typescript" (e.g. for a "ts" file) anything TypeScript-related gets activated.

He also mentioned that there is a workaround for this issue by adding keyword `exact`. Will investigate this. 

I also agree that it is not supposed to open other docset outside the configuration.

**Comment by nikitavoloboev** [comment]
This still fails for me @deerawan 

My settings:

```
  "dash.languageIdToDocsetMap": {
    "typescript": ["typescript", "javascript"]
  },
```

I go to `.ts` file and activate extension.

![2019-03-19 at 11 50](https://user-images.githubusercontent.com/6391776/54600493-3427e100-4a3d-11e9-83f3-14c754ceae66.png)

Result:

![2019-03-19 at 11 50](https://user-images.githubusercontent.com/6391776/54600519-3db14900-4a3d-11e9-8f37-7d932fb23702.png)

**Comment by nikitavoloboev** [comment]
@deerawan Any way to know why this happens? Did I do something wrong?

**Comment by kassi** [comment]
Doesn't work for me anymore, either. I'm pretty sure it worked before and without specifying any sort of language or file name map. Exact keyword doesn't change anything.
