### ISSUE TITLE
Add integration with Velocity Doc

### ISSUE THREAD

**Issue by deerawan** [deerawan/vscode-dash#36]
## Overview
Beside Dash and Zeal, we would love to add integration with Velocity http://velocity.silverlakesoftware.com

**Comment by salembeats** [comment]
Merge my commit so you can close this out and I can get rid of my tweaked copy?

**Comment by salembeats** [comment]
Close issue and merge contributor credit PR?

**Comment by deerawan** [comment]
Implemented in https://github.com/deerawan/vscode-dash/pull/47. Thank you @salembeats!
