### ISSUE TITLE
vscode-dash doesn't detect React as Javascript

### ISSUE THREAD

**Issue by AlexChesters** [deerawan/vscode-dash#4]
If I am inside a `.js` file and I call `ctrl+h` it correctly searches in Javascript.
If I am inside a `.jsx` file and I call `ctrl+h` it searches dash as a whole rather than specifically Javascript.

**Comment by deerawan** [comment]
@AlexChesters Hey alex, I think I know the source of problem. It is because the configuration of javascript in dash doesn't include `.jsx` extension. I'm going to fix it. 

Thank you for submitting the issue. 👍

**Comment by deerawan** [comment]
it is fixed in latest version of vscode-dash `v1.2.0`. 

@AlexChesters Let me know if you still have same problem.
