### ISSUE TITLE
Support to lookup Angular built-in directives

### ISSUE THREAD

**Issue by michaeljota** [deerawan/vscode-dash#43]
When looking for an Angular directive, the search goes about the tag as it would be an html tag. However, it would be nice if this could recognize that its an Angular directive and lookup as such. 

For: `<router-outlet></router-outlet>`

Result: `html,svg,css,bootstrap,foundation,awesome,statamic,javascript,jquery,jqueryui,jquerym,angularjs,backbone,marionette,meteor,moo,prototype,ember,lodash,underscore,sencha,extjs,knockout,zepto,cordova,phonegap,yui:router-outlet`

Expected: `routeroutlet`

**Comment by deerawan** [comment]
@michaeljota I see, seems like we haven't added `angular` docset there in default settings.

**Comment by deerawan** [comment]
@michaeljota I'm afraid that we can't do that to match html tag `<router-outlet>` into angular class `RouterOutlet` in Dash.
