### ISSUE TITLE
Doesn't work with VS Code Vim plugin

### ISSUE THREAD

**Issue by nikitavoloboev** [deerawan/vscode-dash#5]
I tried using ctrl + h to trigger dash search, it didn't do anything. 

Is there any way to fix this? I would also like to remap this hotkey for searching. How can I do that?

Thank you for making this great extension.

**Comment by deerawan** [comment]
Hey @nikitavoloboev, 

Thank you for submitting the issue. 

Does it work without vim plugin?

**Comment by nikitavoloboev** [comment]
Actually ctrl + h works for searching dash but it searches globally and does not scope the result to what file I am currently editing.

I am not using ctrl + alt + h.

**Comment by deerawan** [comment]
@nikitavoloboev thanks for your response 😊

What file extension were you editing?

**Comment by nikitavoloboev** [comment]
An html file.

**Comment by deerawan** [comment]
@nikitavoloboev 
Maybe you can try to change your keyboard shortcut. I've added doc how to change it. 
https://github.com/deerawan/vscode-dash#change-keyboard-shortcut

Let me know if the problem still persists 👍

**Comment by zhang-xun** [comment]
> I tried using ctrl + h to trigger dash search, it didn't do anything.
> 
> Is there any way to fix this? I would also like to remap this hotkey for searching. How can I do that?
> 
> Thank you for making this great extension.

you can Choose in top menu Code -> Preferences -> Keyboard Shortcuts or using shortcuts cmd + K, cmd + S, 
find another vim shortcut (Ctrl+ H), delete it  , and you can  use the dash extension for vscode with vim plugins.
