### ISSUE TITLE
Mark vscode-dash as 'ui' extension

### ISSUE THREAD

**Issue by studoot** [deerawan/vscode-dash#50]
I've started using the VSCode remote extensions for WSL/Docker/SSH, which allow VSCode to run on the developer's computer, but target remote systems and execute certain extensions on the remote system.

It seems to me that Dash is probably one extension that should always be run on the computer running VScode. According to [this page](https://code.visualstudio.com/api/advanced-topics/remote-extensions), this can be achieved by setting the `extensionKind` property in `vscode-dash`'s `package.json`:

```JSON
"extensionKind": "ui"
```

Note to other users: as a workaround, you can mark `vscode-dash` as a ui plugin in your `settings.json`:

```JSON
  "remote.extensionKind": {
    "deerawan.vscode-dash": "ui"
  },
```

**Comment by deerawan** [comment]
Hi @studoot, thank you for letting me know this. I'll go through the page that you gave me then make necessary changes.
