### ISSUE TITLE
Doesn't work at all on my macbook

### ISSUE THREAD

**Issue by jordykoppen** [deerawan/vscode-dash#6]
Hey deerawan,

For some reason Dash doesn't work at all on my Macbook Pro (Sierra 10.12.1) for whatever reason..
Im on VSCode version 1.7.2, when I press ctrl + h or ctrl + alt + H nothing pops up.

Im using it together with the following extensions:
Babel ES6/ES7
ESLint
generate-react-component
jsx
Material-theme
React Redux ES6 Snippets
react-beautify
vscode-icons

I tried using it in JS, CSS and HTML files without success.

If you want more information let me know!
Jordy.

**Comment by deerawan** [comment]
@jordykoppen Hi jordy, thank you for submitting the issue. 

I have tested in Sierra too, it works well. Probably, it got a conflict with other plugins. My suggestion to find the source of problem is to uninstall one by one the plugins you have.

**Comment by srinivasdamam** [comment]
I'm also facing the same issue, is there any way to change the key mapping ? I mean instead `ctrl + h` I would like to use something else.

**Comment by deerawan** [comment]
Hi @srinivasdamam interesting you had same problem. Take a look at the readme here https://github.com/deerawan/vscode-dash#change-keyboard-shortcut.

**Comment by dskoziol** [comment]
I had this same problem, and it ended up being my vscodevim.vim plugin that was interfering with the `ctrl-h` command.
