### ISSUE TITLE
Ctrl + H opens Zeal without requested query (Ctrl+Alt+H works)

### ISSUE THREAD

**Issue by Vojnuk** [deerawan/vscode-dash#68]
I'm working on Visual Studio Code 1.38.1 in Ubuntu 18.04.3 LTS. Here is a screenshot of the problem:

![pic](https://user-images.githubusercontent.com/23299859/66276279-c71d5100-e891-11e9-9303-be80ab2f29eb.png)

Looks like the problem is connected with this area. 
![problem](https://user-images.githubusercontent.com/23299859/66276319-0cda1980-e892-11e9-8240-12fcf7d9e6fb.png)

If I delete all `exact:` prefixes, it works fine.
![possSolution](https://user-images.githubusercontent.com/23299859/66276414-1b750080-e893-11e9-9978-cf9faade666b.png)
![pic1](https://user-images.githubusercontent.com/23299859/66276418-229c0e80-e893-11e9-9fa4-bbb20b72be4d.png)

So, are there any way to remove those `exact:` prefixes without me having to manually delete them?

**Comment by deerawan** [comment]
Hi @Vojnuk, 

Could you check the settings of `Exact Docset` whether it is ticked or not? To disable this, make sure that it is unticked. 

![image](https://user-images.githubusercontent.com/1243921/66278574-26ad4800-e8f6-11e9-9a23-0ead34a88bac.png)

Let me know if the problem still persists. 

Thank you

**Comment by Vojnuk** [comment]
It resolved a problem. 

Thank you very much.
