### ISSUE TITLE
Add support for CMake files

### ISSUE THREAD

**Issue by akdir** [deerawan/vscode-dash#69]
There is no support for CMake files for this extension, eventhough there is already a very good extension on VSCode Marketplace for it and it works really good.

Marketplace extension:
https://marketplace.visualstudio.com/items?itemName=twxs.cmake

**Comment by akdir** [comment]
I use this extension quite alot of times and it is very useful @deerawan. I also like to code in CPP and use CMakefiles quite some time. 

I would like to add support for CMake files for this extension if you let me do it @deerawan.

**Comment by deerawan** [comment]
@akdir thanks for this. Go ahead 😄
