### ISSUE TITLE
Is it possible to make it work with Zeal?

### ISSUE THREAD

**Issue by qcol** [deerawan/vscode-dash#7]

**Comment by deerawan** [comment]
Hi @qcol 

no, it doesn't support Zeal. They are different softwares 😄

**Comment by qcol** [comment]
I know it, so I asked if is it possible to **make to work** ;)

**Comment by qcol** [comment]
By the way... Velocity is also different soft, but one addon for Atrom works with all Velocity, Dash and Zeal :)  https://atom.io/packages/dash
