### ISSUE TITLE
Add support for Latex

### ISSUE THREAD

**Issue by akdir** [deerawan/vscode-dash#70]
There is no support for latex for this extension. Latex is used by alot of people and the extension on VSCode Marketplace is popular.

Marketplace extension:
https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop

**Comment by akdir** [comment]
I would also like to add Latex support for this extension @deerawan.

**Comment by deerawan** [comment]
@akdir Go ahead 👍
