### ISSUE TITLE
Add support for Zeal installed as Flatpak

### ISSUE THREAD

**Issue by David-Else** [deerawan/vscode-dash#74]
I switched to using Zeal as a flatpak and now vscode-dash no longer works when I press ctrl-h.

It needs to be called with `flatpak run org.zealdocs.Zeal/x86_64/stable`

Cheers!

**Comment by David-Else** [comment]
Looks like it is not happening, hopefully the new Zeal will come out soon and I won't need to rely on the flatpak version.

**Comment by gotohr** [comment]
maybe there is a better way, but I just created `~/bin/zeal`
```
#!/bin/bash
flatpak run org.zealdocs.Zeal/x86_64/stable "$@"
```
`~/bin` is in my `PATH`

**Comment by Merrit** [comment]
> maybe there is a better way, but I just created `~/bin/zeal`
> 
> ```
> #!/bin/bash
> flatpak run org.zealdocs.Zeal/x86_64/stable "$@"
> ```
> 
> `~/bin` is in my `PATH`

Thanks, this just got it working for me again! :blue_heart:
