### ISSUE TITLE
Add support for Dash 5

### ISSUE THREAD

**Issue by lada** [deerawan/vscode-dash#79]
The extension does not seem to work with the new version of Dash (5.0). The app opens, but the search field is empty.

**Comment by deerawan** [comment]
@lada hey, thank you for raising the issue. I'll check its compatibility soon.

**Comment by deerawan** [comment]
@lada I tried Dash 5 and it works, the search field is filled

<img width="1101" alt="Screen Shot 2019-12-13 at 03 26 58" src="https://user-images.githubusercontent.com/1243921/70730129-8857bb80-1d58-11ea-879f-13b8f199dc37.png">

could you give me more information?

**Comment by lada** [comment]
@deerawan Thanks a lot for you feedback! I've reinstalled Dash and now it works fine. I don't know what happened, probably some problem with the update...
