### ISSUE TITLE
Dash plugin doesn't work on mac os Sierra & VSCode 1.10.1 || 1.11.0

### ISSUE THREAD

**Issue by thadjbullet** [deerawan/vscode-dash#9]
Hi. When i'm use ctrl+h it's show me this "warning" popup. I tried on various types of files with the same result. Change hotkeys does not change anything. 
Thanks!
![2017-03-05_14-55-45](https://cloud.githubusercontent.com/assets/17276356/23587031/e8fb53d4-01b3-11e7-9651-7fa6a2460286.png)

**Comment by deerawan** [comment]
Hi @thadjbullet, interesting case, I use Sierra and VSCode 1.10.1 too and don't get this problem. What VSCode Dash version do you use? Have you tried to reinstall the plugin?

**Comment by thadjbullet** [comment]
Yep, several times. Right now I update plugin to 1.4.0 and have the same issue.

**Comment by deerawan** [comment]
@thadjbullet do you encounter same problem with other plugins? Have it worked in previous version?

**Comment by thadjbullet** [comment]
@deerawan The issue is solved. The problem was with the plugin vscode-icons.

**Comment by deerawan** [comment]
@thadjbullet sweet 👍
