### ISSUE TITLE
Velocity Integration

### ISSUE THREAD

**Issue by davidtaylorjr** [deerawan/vscode-dash#90]
How do I set this to open Velocity docs?

**Comment by deerawan** [comment]
@davidtaylorjr Hi David, currently, it is automatically configured based on OS ie. if you use Windows, it uses Velocity. 

Do you have another use case?

**Comment by davidtaylorjr** [comment]
I do have Velocity installed on Windows but it says the program can't be
found...

**Comment by davidtaylorjr** [comment]
I had to get a new pc today and insalled velocity fresh and it works fine. I am wondering if the fact I had zeal and uninstalled it on my other machine caused the issue...
